version: '3.8'

services:
  inference-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=distilbert-base-uncased-finetuned-sst-2-english
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  # Uncomment for GPU serving (requires nvidia-docker)
  # inference-cuda:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.cuda
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - MODEL_NAME=distilbert-base-uncased-finetuned-sst-2-english
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s
  #   restart: unless-stopped
