[project]
name = "transformers-stack"
version = "0.1.0"
description = "A cohesive Transformers stack built on PyTorch with uv for reproducible dependency management"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "EvalOps", email = "contact@evalops.com" }
]

dependencies = [
  "torch==2.8.0",
  "transformers[torch]==4.56.2",
  "datasets==4.1.1",
  "evaluate>=0.4.1",
  "scikit-learn>=1.3",
  # performance & fine-tuning
  "accelerate==1.10.1",
  "peft==0.17.1",
  "bitsandbytes==0.47.0",
  "flash-attn==2.8.3",
  "xformers==0.0.32.post2",
  "vllm==0.10.2",
  # utilities
  "sentencepiece>=0.1.99",
  "tqdm>=4.66",
]

[project.optional-dependencies]
dev = [
  "ruff",
  "black",
  "pytest",
  "ipykernel",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
